{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.fluttermodule.flutter_module",
    "module": "flutter",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-debug.aar",
          "url": "flutter-1.0-debug.aar",
          "size": 11714105,
          "sha512": "910f4d56b0b257d1faf457c2bf77f74ff9f5b8a6a6fa93a7dfa54803f54af7938866f354c0c92f8be93c26b98111dd91a5eca24299f4bd1e7d1bca017c78ed2d",
          "sha256": "0ddb634447db2b52e0700df9f874cecc7c31bd00996e32190d333f9c8f742dd0",
          "sha1": "d75d829b15b87199f3152b7e14d74cca98370af4",
          "md5": "ba5465740e7da571382053bc950db24b"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-debug.aar",
          "url": "flutter-1.0-debug.aar",
          "size": 11714105,
          "sha512": "910f4d56b0b257d1faf457c2bf77f74ff9f5b8a6a6fa93a7dfa54803f54af7938866f354c0c92f8be93c26b98111dd91a5eca24299f4bd1e7d1bca017c78ed2d",
          "sha256": "0ddb634447db2b52e0700df9f874cecc7c31bd00996e32190d333f9c8f742dd0",
          "sha1": "d75d829b15b87199f3152b7e14d74cca98370af4",
          "md5": "ba5465740e7da571382053bc950db24b"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-release.aar",
          "url": "flutter-1.0-release.aar",
          "size": 3721810,
          "sha512": "5c7e5a59ac22d6e99c41d80671de2817d4158c9b19c52951c69b2f13354bcdcb8937dd1bbae70bd90b53634470403e1baed245fd0105ba14d6c881a8b146dd14",
          "sha256": "f574aae35afe6a2ce6f97e6b2c5235f0aa19f75a16be9585be23cf4d14d2fa1f",
          "sha1": "9964893fe0517a26c15ec6fa4097ec245df4f553",
          "md5": "e046a68f9a9f44aa32dca788af4a5fc0"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-release.aar",
          "url": "flutter-1.0-release.aar",
          "size": 3721810,
          "sha512": "5c7e5a59ac22d6e99c41d80671de2817d4158c9b19c52951c69b2f13354bcdcb8937dd1bbae70bd90b53634470403e1baed245fd0105ba14d6c881a8b146dd14",
          "sha256": "f574aae35afe6a2ce6f97e6b2c5235f0aa19f75a16be9585be23cf4d14d2fa1f",
          "sha1": "9964893fe0517a26c15ec6fa4097ec245df4f553",
          "md5": "e046a68f9a9f44aa32dca788af4a5fc0"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-profile.aar",
          "url": "flutter-1.0-profile.aar",
          "size": 203765,
          "sha512": "7936bda93a4926148f23f432113314bc3c1d6471be8ad150e41ed9f87d11d654985720e5682a55778a0620d16c7467340e189e5839a68a442eb16633bc05bfac",
          "sha256": "582b1e69efa8b3060b7c7ea53b19da46725545f45c05a6a11652c5873db4e397",
          "sha1": "d7d2f1bc533857152bb9636d94e9d8662b465c4f",
          "md5": "611d56355e115d89d885e66f59282e23"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-profile.aar",
          "url": "flutter-1.0-profile.aar",
          "size": 203765,
          "sha512": "7936bda93a4926148f23f432113314bc3c1d6471be8ad150e41ed9f87d11d654985720e5682a55778a0620d16c7467340e189e5839a68a442eb16633bc05bfac",
          "sha256": "582b1e69efa8b3060b7c7ea53b19da46725545f45c05a6a11652c5873db4e397",
          "sha1": "d7d2f1bc533857152bb9636d94e9d8662b465c4f",
          "md5": "611d56355e115d89d885e66f59282e23"
        }
      ]
    }
  ]
}
