{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sofka.sofkafluttermodule.sofka_flutter_module",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 4703687,
          "sha512": "3d0fee269e5ed3aad77b191ea6083142dcb015c5abec83f854f79aa70bdb43cd72ba7f9d8358b78faec43c2ad37f8f0c447b01e4912141065a0b55ef8c6c32ea",
          "sha256": "b5ef11ce67a22db7b002b871ca459f478cfe556cb0f7c13023d3932829d999bd",
          "sha1": "843a85d317caf10f158c646ffd23c5410ed0d22a",
          "md5": "9023eb85d31adb71ff924965e2d92033"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 4703687,
          "sha512": "3d0fee269e5ed3aad77b191ea6083142dcb015c5abec83f854f79aa70bdb43cd72ba7f9d8358b78faec43c2ad37f8f0c447b01e4912141065a0b55ef8c6c32ea",
          "sha256": "b5ef11ce67a22db7b002b871ca459f478cfe556cb0f7c13023d3932829d999bd",
          "sha1": "843a85d317caf10f158c646ffd23c5410ed0d22a",
          "md5": "9023eb85d31adb71ff924965e2d92033"
        }
      ]
    }
  ]
}
