{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.fluttermodule.flutter_module",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3721810,
          "sha512": "5c7e5a59ac22d6e99c41d80671de2817d4158c9b19c52951c69b2f13354bcdcb8937dd1bbae70bd90b53634470403e1baed245fd0105ba14d6c881a8b146dd14",
          "sha256": "f574aae35afe6a2ce6f97e6b2c5235f0aa19f75a16be9585be23cf4d14d2fa1f",
          "sha1": "9964893fe0517a26c15ec6fa4097ec245df4f553",
          "md5": "e046a68f9a9f44aa32dca788af4a5fc0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3721810,
          "sha512": "5c7e5a59ac22d6e99c41d80671de2817d4158c9b19c52951c69b2f13354bcdcb8937dd1bbae70bd90b53634470403e1baed245fd0105ba14d6c881a8b146dd14",
          "sha256": "f574aae35afe6a2ce6f97e6b2c5235f0aa19f75a16be9585be23cf4d14d2fa1f",
          "sha1": "9964893fe0517a26c15ec6fa4097ec245df4f553",
          "md5": "e046a68f9a9f44aa32dca788af4a5fc0"
        }
      ]
    }
  ]
}
